# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_form(object):
    def setupUi(self, edit_form):
        edit_form.setObjectName("edit_form")
        edit_form.setWindowModality(QtCore.Qt.NonModal)
        edit_form.resize(650, 266)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(edit_form.sizePolicy().hasHeightForWidth())
        edit_form.setSizePolicy(sizePolicy)
        edit_form.setMinimumSize(QtCore.QSize(650, 266))
        edit_form.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"font-family:Microsoft Yahei;")
        edit_form.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(edit_form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(600, 200))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid #C6C6C6;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.le_school_id = QtWidgets.QLineEdit(self.widget_4)
        self.le_school_id.setStyleSheet("border:1px solid #C6C6C6;")
        self.le_school_id.setObjectName("le_school_id")
        self.gridLayout.addWidget(self.le_school_id, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_name = QtWidgets.QLineEdit(self.widget_5)
        self.le_name.setStyleSheet("border:1px solid #C6C6C6;")
        self.le_name.setObjectName("le_name")
        self.gridLayout_2.addWidget(self.le_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_5, 0, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.cb_gender = QtWidgets.QComboBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_gender.sizePolicy().hasHeightForWidth())
        self.cb_gender.setSizePolicy(sizePolicy)
        self.cb_gender.setStyleSheet("border:1px solid #C6C6C6;")
        self.cb_gender.setObjectName("cb_gender")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.gridLayout_3.addWidget(self.cb_gender, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.widget_6, 1, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_3)
        self.widget_7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.le_age = QtWidgets.QLineEdit(self.widget_7)
        self.le_age.setStyleSheet("border:1px solid #C6C6C6;")
        self.le_age.setObjectName("le_age")
        self.gridLayout_4.addWidget(self.le_age, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_7, 1, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        self.widget_9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.le_phone = QtWidgets.QLineEdit(self.widget_9)
        self.le_phone.setStyleSheet("border:1px solid #C6C6C6;")
        self.le_phone.setObjectName("le_phone")
        self.gridLayout_8.addWidget(self.le_phone, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_9)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_9, 2, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.widget_3)
        self.widget_10.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.le_address = QtWidgets.QLineEdit(self.widget_10)
        self.le_address.setStyleSheet("border:1px solid #C6C6C6;")
        self.le_address.setObjectName("le_address")
        self.gridLayout_9.addWidget(self.le_address, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_10, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 10))
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_7.addWidget(self.widget_8, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius:0px;\n"
"    background-color: rgb(225, 225, 225);\n"
"    border:1px solid #C6C6C6;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(198, 198, 198);\n"
"    border-color: rgb(150, 150, 150);\n"
"    border:1px solid #C6C6C6;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(177, 177, 177);\n"
"    border:1px solid #C6C6C6;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setContentsMargins(0, 5, -1, 5)
        self.gridLayout_6.setHorizontalSpacing(20)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btn_cancel = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setMinimumSize(QtCore.QSize(50, 0))
        self.btn_cancel.setObjectName("btn_cancel")
        self.gridLayout_6.addWidget(self.btn_cancel, 0, 0, 1, 1)
        self.btn_save = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setMinimumSize(QtCore.QSize(50, 0))
        self.btn_save.setObjectName("btn_save")
        self.gridLayout_6.addWidget(self.btn_save, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.widget_2, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 2)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.gridLayout_5.addWidget(self.widget, 1, 0, 1, 1)
        edit_form.setCentralWidget(self.centralwidget)

        self.retranslateUi(edit_form)
        QtCore.QMetaObject.connectSlotsByName(edit_form)

    def retranslateUi(self, edit_form):
        _translate = QtCore.QCoreApplication.translate
        edit_form.setWindowTitle(_translate("edit_form", "Edit Form"))
        self.label.setText(_translate("edit_form", "学号："))
        self.label_2.setText(_translate("edit_form", "姓名："))
        self.label_3.setText(_translate("edit_form", "性别："))
        self.cb_gender.setItemText(0, _translate("edit_form", "男"))
        self.cb_gender.setItemText(1, _translate("edit_form", "女"))
        self.label_4.setText(_translate("edit_form", "年龄："))
        self.label_5.setText(_translate("edit_form", "联系电话："))
        self.label_6.setText(_translate("edit_form", "家庭住址："))
        self.btn_cancel.setText(_translate("edit_form", "取消"))
        self.btn_save.setText(_translate("edit_form", "保存"))
